-- Catalogo de disenos por negocio: la clienta ve los trabajos reales del
-- salon, vota cuanto le gusta cada uno y reserva directamente el que quiere.
-- Ejecutar una sola vez en Supabase SQL Editor. Sirve para todos los negocios.

-- ============================================
-- 1. DISENOS DEL CATALOGO
-- ============================================
CREATE TABLE IF NOT EXISTS public.catalogo_disenos (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  negocio_id uuid NOT NULL REFERENCES public.negocios(id) ON DELETE CASCADE,
  titulo text NOT NULL,
  descripcion text,
  imagen_url text NOT NULL,
  categoria text DEFAULT 'general',
  -- servicio_id va como TEXT a proposito: las apps guardan el id del servicio
  -- con tipos distintos segun la antiguedad del negocio y aqui solo se usa
  -- para preseleccionar el servicio al reservar, nunca para integridad.
  servicio_id text,
  servicio_nombre text,
  orden integer DEFAULT 99,
  activo boolean DEFAULT true,
  -- Promedio precalculado por trigger: la galeria carga en UNA sola consulta
  -- en vez de pedir los votos de cada diseno (clave con 3G en Cuba).
  votos_suma integer NOT NULL DEFAULT 0,
  votos_conteo integer NOT NULL DEFAULT 0,
  created_at timestamptz DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_catalogo_disenos_negocio
ON public.catalogo_disenos (negocio_id, activo, orden, id DESC);

-- ============================================
-- 2. VOTOS DE LAS CLIENTAS (0-100, tipo "cuanto te gusta")
-- ============================================
CREATE TABLE IF NOT EXISTS public.catalogo_votos (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  diseno_id bigint NOT NULL REFERENCES public.catalogo_disenos(id) ON DELETE CASCADE,
  -- Huella del dispositivo guardada en localStorage. No identifica a nadie:
  -- solo evita que el mismo telefono infle un diseno votando 200 veces.
  dispositivo text NOT NULL,
  puntuacion smallint NOT NULL CHECK (puntuacion >= 0 AND puntuacion <= 100),
  nombre text,
  created_at timestamptz DEFAULT now(),
  UNIQUE (diseno_id, dispositivo)
);

CREATE INDEX IF NOT EXISTS idx_catalogo_votos_diseno
ON public.catalogo_votos (diseno_id);

-- ============================================
-- 3. TRIGGER: mantener suma y conteo al dia
-- ============================================
CREATE OR REPLACE FUNCTION public.catalogo_recalcular_votos()
RETURNS TRIGGER AS $$
BEGIN
  IF (TG_OP = 'INSERT') THEN
    UPDATE public.catalogo_disenos
    SET votos_suma = votos_suma + NEW.puntuacion,
        votos_conteo = votos_conteo + 1
    WHERE id = NEW.diseno_id;
  ELSIF (TG_OP = 'UPDATE') THEN
    -- Cambiar el voto (mismo dispositivo) no debe sumar un votante nuevo.
    UPDATE public.catalogo_disenos
    SET votos_suma = votos_suma - OLD.puntuacion + NEW.puntuacion
    WHERE id = NEW.diseno_id;
  ELSIF (TG_OP = 'DELETE') THEN
    UPDATE public.catalogo_disenos
    SET votos_suma = GREATEST(0, votos_suma - OLD.puntuacion),
        votos_conteo = GREATEST(0, votos_conteo - 1)
    WHERE id = OLD.diseno_id;
  END IF;
  RETURN NULL;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_catalogo_votos ON public.catalogo_votos;
CREATE TRIGGER trg_catalogo_votos
AFTER INSERT OR UPDATE OR DELETE ON public.catalogo_votos
FOR EACH ROW EXECUTE FUNCTION public.catalogo_recalcular_votos();

-- ============================================
-- 4. DISENO ELEGIDO EN LA RESERVA
-- ============================================
ALTER TABLE public.reservas
ADD COLUMN IF NOT EXISTS diseno_titulo text,
ADD COLUMN IF NOT EXISTS diseno_imagen_url text;

COMMENT ON COLUMN public.reservas.diseno_titulo IS
'Diseno del catalogo que eligio la clienta al reservar (solo informativo para el salon).';

-- ============================================
-- 5. RLS: igual que el resto del proyecto (acceso publico controlado por app)
-- ============================================
ALTER TABLE public.catalogo_disenos ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "catalogo_disenos_select" ON public.catalogo_disenos;
CREATE POLICY "catalogo_disenos_select"
ON public.catalogo_disenos FOR SELECT USING (true);

DROP POLICY IF EXISTS "catalogo_disenos_insert" ON public.catalogo_disenos;
CREATE POLICY "catalogo_disenos_insert"
ON public.catalogo_disenos FOR INSERT WITH CHECK (true);

DROP POLICY IF EXISTS "catalogo_disenos_update" ON public.catalogo_disenos;
CREATE POLICY "catalogo_disenos_update"
ON public.catalogo_disenos FOR UPDATE USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "catalogo_disenos_delete" ON public.catalogo_disenos;
CREATE POLICY "catalogo_disenos_delete"
ON public.catalogo_disenos FOR DELETE USING (true);

ALTER TABLE public.catalogo_votos ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "catalogo_votos_select" ON public.catalogo_votos;
CREATE POLICY "catalogo_votos_select"
ON public.catalogo_votos FOR SELECT USING (true);

DROP POLICY IF EXISTS "catalogo_votos_insert" ON public.catalogo_votos;
CREATE POLICY "catalogo_votos_insert"
ON public.catalogo_votos FOR INSERT WITH CHECK (true);

DROP POLICY IF EXISTS "catalogo_votos_update" ON public.catalogo_votos;
CREATE POLICY "catalogo_votos_update"
ON public.catalogo_votos FOR UPDATE USING (true) WITH CHECK (true);
